{{- if .Values.worker.enabled }}
{{- if eq (.Values.worker.workload | lower) "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with (mergeOverwrite (deepCopy .Values.global.deploymentAnnotations) .Values.worker.deploymentAnnotations) }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  name: {{ template "application.worker.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "application.worker.labels" . | nindent 4 }}
spec:
  {{- with (mergeOverwrite (deepCopy .Values.global.deploymentStrategy) .Values.worker.deploymentStrategy) }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicas }}
  {{- end }}
  minReadySeconds: {{ .Values.global.minReadySeconds }}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "application.worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.global.env }}
        checksum/configmap: {{ include (print $.Template.BasePath "/worker/config-map.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.global.vault.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/worker/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with (mergeOverwrite (deepCopy .Values.global.podAnnotations) .Values.worker.podAnnotations) }}
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
      labels:
        {{- include "application.worker.selectorLabels" . | nindent 8 }}
        {{- include "application.worker.labels" . | nindent 8 }}
        {{- with (mergeOverwrite (deepCopy .Values.global.podLabels) .Values.worker.podLabels) }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.worker.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.worker.terminationGracePeriodSeconds }}
      {{- end }}
      serviceAccountName: {{ include "worker.serviceAccountName" . }}
      containers:
      - name: {{ .Values.worker.name }}
        {{- with (.Values.worker.image.repository | default .Values.global.image.repository) }}
        {{- if contains "/" ($.Values.worker.image.repository | default $.Values.global.image.repository) }}
        image: "{{ . }}:{{- include "application.worker.image.tag" $ }}"
        {{- else }}
        image: "{{ $.Values.worker.image.hub | default $.Values.global.image.hub }}/{{ $.Values.worker.image.repository | default $.Values.global.image.repository }}:{{- include "application.worker.image.tag" $ }}"
        {{- end }}
        {{- end }}
        imagePullPolicy: {{ .Values.worker.image.imagePullPolicy | default .Values.global.image.imagePullPolicy }}
        {{- if .Values.worker.extraCommands }}
        command:
        {{- with .Values.worker.extraCommands }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- if .Values.worker.extraArgs }}
        args:
        {{- with .Values.worker.extraArgs }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- with .Values.worker.extraEnvs }}
        env:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        envFrom:
        {{- if .Values.global.env  }}
          - configMapRef:
              name: {{ include "application.worker.name" . }}-env
        {{- end }}
        {{- if .Values.global.vault.enabled  }}
          - secretRef:
              name: {{ include "application.worker.name" . }}
        {{- end }}
        {{- with .Values.worker.envFrom }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.worker.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        {{- range .Values.worker.ports }}
          - name: {{ .name }}
            containerPort: {{ .targetPort }}
            protocol: TCP
        {{- end }}
        {{- with .Values.worker.livenessProbe }}
        livenessProbe:
          httpGet:
            path: {{ .httpGet.path }}
            port: {{ .httpGet.port }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
          successThreshold: {{ .successThreshold }}
          failureThreshold: {{ .failureThreshold }}
        {{- end }}
        {{- with .Values.worker.readinessProbe }}
        readinessProbe:
          httpGet:
            path: {{ .httpGet.path }}
            port: {{ .httpGet.port }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
          successThreshold: {{ .successThreshold }}
          failureThreshold: {{ .failureThreshold }}
        {{- end }}
        resources:
          {{- toYaml .Values.worker.resources | nindent 10 }}
        {{- with .Values.worker.lifecycle }}
        lifecycle:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.worker.initContainers }}
      initContainers:
      {{- range $index, $container := . }}
      {{- with $container }}
        - name: {{ .name }}
          {{- if contains "/" .image.repository }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          {{- else }}
          image: "{{ .image.hub }}/{{ .image.repository }}:{{ .image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .image.imagePullPolicy }}
          {{- toYaml .container | nindent 10 }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- with .Values.worker.affinity | default .Values.global.affinity  }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.topologySpreadConstraints | default .Values.global.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range $constraint := . }}
      - {{ toYaml $constraint | nindent 8 | trim }}
        {{- if not $constraint.labelSelector }}
        labelSelector:
          matchLabels:
            {{- include "application.worker.selectorLabels" $ | nindent 12 }}
        {{- end }}
        {{- end }}
      {{- end }}
      {{- with .Values.worker.volumes }}
      volumes:
        {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
{{- end }}
