{{- if .Values.worker.istio.enabled }}
{{- if .Values.worker.istio.ingressGateways }}
{{- range $index, $gateway := .Values.worker.istio.ingressGateways }}
{{- with $gateway }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .name }}
  labels:
    {{- include "application.worker.labels" $ | nindent 4 }}
spec:
  selector:
    {{- toYaml .selector | nindent 4}}
  servers:
    {{- toYaml .servers | nindent 4 }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
