{{- if .Values.worker.enabled }}
{{- if .Values.worker.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "application.worker.name" . }}
  labels:
    {{- include "application.worker.labels" . | nindent 4 }}
spec:
  {{- with .Values.worker.pdb.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- else }}
  minAvailable: {{ .Values.worker.pdb.minAvailable | default 0 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "application.worker.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
