{{- if .Values.worker.enabled }}
{{- if .Values.worker.priorityClass.create }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.worker.priorityClass.name | default (include "application.worker.name" .) }}
  labels:
    {{- include "application.worker.labels" . | nindent 4 }}
value: {{ .Values.worker.priorityClass.value }}
{{- with .Values.worker.priorityClass.preemptionPolicy }}
preemptionPolicy: {{ . }}
{{- end }}
globalDefault: {{ .Values.worker.priorityClass.globalDefault | default false }}
{{- with .Values.worker.priorityClass.description }}
description: {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}
