{{- if and .Values.global.observability.prometheus.enabled .Values.global.observability.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "application.name" . }}
  labels:
    {{- include "application.commonLabels" . | nindent 4 }}
spec:
  endpoints:
    - path: {{ .Values.global.observability.prometheus.path }}
      port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "application.commonLabels" . | nindent 6}}
{{- end }}
