{{- if .Values.server.enabled }}
{{- if .Values.global.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "application.server.name" . }}
  labels:
    {{- include "application.server.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.global.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.global.externalSecret.store.kind }}
    name: {{ .Values.global.externalSecret.store.name }}
  target:
    name: {{ include "application.server.externalSecretName" . }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.global.externalSecret.path }}
{{- end }}
{{- end }}
