{{- if .Values.server.enabled }}
{{- if .Values.global.vault.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.server.name" . }}
  labels:
    {{- include "application.server.labels" . | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: {{ .Values.global.vault.path }}
type: Opaque
stringData:
  {{- toYaml .Values.global.vault.secrets | nindent 2 }}
{{- end }}
{{- end }}
---
{{- if .Values.server.enabled }}
{{- range $index, $secret := .Values.server.extraSecrets }}
{{- with $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- include "application.server.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: {{ .type }}
stringData:
  {{- toYaml .secrets | nindent 2 }}
{{- end }}
---
{{- end }}
{{- end }}
