{{- if .Values.server.enabled }}
{{- if .Values.server.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "application.labels" $ | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy .Values.global.serviceAccount.labels) .Values.server.serviceAccount.labels ) }}
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- with (mergeOverwrite (deepCopy .Values.global.serviceAccount.annotations) .Values.server.serviceAccount.annotations) }}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- with (concat .Values.global.serviceAccount.imagePullSecrets .Values.server.serviceAccount.imagePullSecrets) }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
