{{- if .Values.hook.enabled }}
{{- range $jobIndex, $job := .Values.hook.jobs }}
{{- with $job.vault }}
{{- if .enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name | default (printf "%s-%s" $.Release.Name $job.name | trunc 63 | trimSuffix "-") }}
  labels:
    {{- include "application.commonLabels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    avp.kubernetes.io/path: {{ .path }}
    "helm.sh/hook": {{ .hook | default "pre-install" | quote }}
    {{- if .hookWeight }}
    "helm.sh/hook-weight": {{ .hookWeight | quote }}
    {{- end }}
    {{- if .hookDeletePolicy }}
    "helm.sh/hook-delete-policy": {{ .hookDeletePolicy | join "," | quote }}
    {{- else }}
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
    {{- end }}
type: Opaque
stringData:
  {{- toYaml .secrets | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
