{{- range $jobIndex, $job := .Values.hook.jobs }}
{{- if $job.enabled }}
{{- with $job.serviceAccount }}
{{- if .create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name | default (printf "%s-%s" $.Release.Name $job.name | trunc 63 | trimSuffix "-") }}
  namespace: {{ $.Release.Namespace }}
  labels:
  {{- include "application.commonLabels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with (mergeOverwrite (deepCopy $.Values.global.serviceAccount.annotations) (.annotations | default dict)) }}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  "helm.sh/hook": {{ .hook | default "pre-install" | quote }}
  {{- if .hookWeight }}
  "helm.sh/hook-weight": {{ .hookWeight | quote }}
  {{- end }}
  {{- if .hookDeletePolicy }}
  "helm.sh/hook-delete-policy": {{ .hookDeletePolicy | join "," | quote }}
  {{- else }}
  "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
  {{- end }}
  {{- with $.Values.global.imagePullSecrets }}
  imagePullSecrets:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
