{{- if .Values.vault.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.name" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: {{ .Values.vault.path }}
type: Opaque
stringData:
  {{- toYaml .Values.vault.secrets | nindent 2 }}
{{- end }}
---
{{- range $index, $secret := .Values.extraSecrets }}
{{- with $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: {{ .type }}
stringData:
  {{- toYaml .secrets | nindent 2 }}
{{- end }}
---
{{- end }}
