{{- if .Values.scheduler.enabled }}
{{- if .Values.global.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.scheduler.name" . }}-env
  labels:
    {{- include "application.scheduler.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.global.env | nindent 2 }}
{{- end }}
{{- end }}
---
{{- range $index, $configMap := .Values.scheduler.extraConfigMaps }}
{{- with $configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  labels:
    {{- include "application.scheduler.labels" $ | nindent 4 }}
data:
  {{- toYaml .data | nindent 2 }}
{{- end }}
---
{{- end }}
