{{- if .Values.scheduler.enabled }}
{{- if .Values.scheduler.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: {{ include "application.scheduler.name" . }}
    labels:
    {{- include "application.scheduler.labels" . | nindent 8 }}
spec:
    {{- with .Values.scheduler.autoscaling.scaleTargetRef }}
    scaleTargetRef:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    minReplicas: {{ .Values.scheduler.autoscaling.minReplicas }}
    maxReplicas: {{ .Values.scheduler.autoscaling.maxReplicas }}
    metrics:
      {{- with .Values.scheduler.autoscaling.targetMemoryUtilizationPercentage }}
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: {{ . }}
      {{- end }}
      {{- with .Values.scheduler.autoscaling.targetCPUUtilizationPercentage }}
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: {{ . }}
      {{- end }}
    {{- with .Values.scheduler.autoscaling.behavior }}
    behavior:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
