{{- if .Values.scheduler.enabled }}
{{- if eq (.Values.scheduler.workload | lower) "rollout" }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  {{- with (mergeOverwrite (deepCopy .Values.global.deploymentAnnotations) .Values.scheduler.deploymentAnnotations) }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  name: {{ template "application.scheduler.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "application.scheduler.labels" . | nindent 4 }}
spec:
  {{- with (mergeOverwrite (deepCopy .Values.global.deploymentStrategy) .Values.scheduler.deploymentStrategy) }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (mergeOverwrite (deepCopy .Values.global.rolloutAnalysis) .Values.scheduler.rolloutAnalysis) }}
  analysis:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if not .Values.scheduler.autoscaling.enabled }}
  replicas: {{ .Values.scheduler.replicas }}
  {{- end }}
  minReadySeconds: {{ .Values.global.minReadySeconds }}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "application.scheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.global.env }}
        checksum/configmap: {{ include (print $.Template.BasePath "/scheduler/config-map.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.global.vault.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/scheduler/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with (mergeOverwrite (deepCopy .Values.global.podAnnotations) .Values.scheduler.podAnnotations) }}
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
      labels:
        {{- include "application.scheduler.selectorLabels" . | nindent 8 }}
        {{- include "application.scheduler.labels" . | nindent 8 }}
        {{- with (mergeOverwrite (deepCopy .Values.global.podLabels) .Values.scheduler.podLabels) }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.scheduler.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.scheduler.terminationGracePeriodSeconds }}
      {{- end }}
      serviceAccountName: {{ include "scheduler.serviceAccountName" . }}
      containers:
      - name: {{ .Values.scheduler.name }}
        {{- with (.Values.scheduler.image.repository | default .Values.global.image.repository) }}
        {{- if contains "/" ($.Values.scheduler.image.repository | default $.Values.global.image.repository) }}
        image: "{{ . }}:{{ $.Values.scheduler.image.tag | default $.Values.global.image.tag }}"
        {{- else }}
        image: "{{ $.Values.scheduler.image.hub | default $.Values.global.image.hub }}/{{ $.Values.scheduler.image.repository | default $.Values.global.image.repository }}:{{ $.Values.scheduler.image.tag | default $.Values.global.image.tag }}"
        {{- end }}
        {{- end }}
        imagePullPolicy: {{ .Values.scheduler.image.imagePullPolicy | default .Values.global.image.imagePullPolicy }}
        {{- if .Values.scheduler.extraCommands }}
        command:
        {{- with .Values.scheduler.extraCommands }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- if .Values.scheduler.extraArgs }}
        args:
        {{- with .Values.scheduler.extraArgs }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- with .Values.scheduler.extraEnvs }}
        env:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        envFrom:
        {{- if .Values.global.env  }}
          - configMapRef:
              name: {{ include "application.scheduler.name" . }}-env
        {{- end }}
        {{- if .Values.global.vault.enabled  }}
          - secretRef:
              name: {{ include "application.scheduler.name" . }}
        {{- end }}
        {{- with .Values.scheduler.envFrom }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.scheduler.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        {{- range .Values.scheduler.ports }}
          - name: {{ .name }}
            containerPort: {{ .targetPort }}
            protocol: TCP
        {{- end }}
        {{- if .Values.global.observability.prometheus.enabled }}
          - name: metrics
            containerPort: {{ default .Values.global.observability.prometheus.port .Values.global.observability.prometheus.targetPort }}
            protocol: TCP
        {{- end }}
        {{- with .Values.scheduler.livenessProbe }}
        livenessProbe:
          httpGet:
            path: {{ .httpGet.path }}
            port: {{ .httpGet.port }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
          successThreshold: {{ .successThreshold }}
          failureThreshold: {{ .failureThreshold }}
        {{- end }}
        {{- with .Values.scheduler.readinessProbe }}
        readinessProbe:
          httpGet:
            path: {{ .httpGet.path }}
            port: {{ .httpGet.port }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
          successThreshold: {{ .successThreshold }}
          failureThreshold: {{ .failureThreshold }}
        {{- end }}
        resources:
          {{- toYaml .Values.scheduler.resources | nindent 10 }}
        {{- with .Values.scheduler.lifecycle }}
        lifecycle:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.scheduler.initContainers }}
      initContainers:
      {{- range $index, $container := . }}
      {{- with $container }}
        - name: {{ .name }}
          {{- if contains "/" .image.repository }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          {{- else }}
          image: "{{ .image.hub }}/{{ .image.repository }}:{{ .image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .image.imagePullPolicy }}
          {{- toYaml .container | nindent 10 }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- with .Values.scheduler.affinity | default .Values.global.affinity  }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.topologySpreadConstraints | default .Values.global.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range $constraint := . }}
      - {{ toYaml $constraint | nindent 8 | trim }}
        {{- if not $constraint.labelSelector }}
        labelSelector:
          matchLabels:
            {{- include "application.scheduler.selectorLabels" . | nindent 12 }}
        {{- end }}
        {{- end }}
      {{- end }}
      {{- with .Values.scheduler.volumes }}
      volumes:
        {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
{{- end }}
