{{- if .Values.scheduler.enabled }}
{{- if .Values.scheduler.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scheduler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "application.scheduler.labels" $ | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy .Values.global.serviceAccount.labels) .Values.scheduler.serviceAccount.labels ) }}
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- with (mergeOverwrite (deepCopy .Values.global.serviceAccount.annotations) .Values.scheduler.serviceAccount.annotations) }}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- with (concat .Values.global.serviceAccount.imagePullSecrets .Values.scheduler.serviceAccount.imagePullSecrets) }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
